### ISSUE TITLE
if requiredEncodings is empty then we have no labels

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi-reactive#30]
[Add X in required encodings for bubble rank to enable labels!](https://github.com/Gapminder/tools-page/commit/12f18d9bc7e9fb383bbb71c47dc7c3a88741ddc2)

only if 'x' added to requiredEncodings then we have 'label' in frames

if requiredEncodings is empty then we have fulljoin for encoding data in dataMapCache. but 'label' data is 'lookups' dataframe which does not have coded iterators yet ). we have warning "Invalid operation. Generated dataframe iterator not yet implemented." and miss 'label' in datamapcache.
https://github.com/vizabi/vizabi-reactive/blob/master/src/core/marker/baseMarker.js#L146
with 'x' in requiredEncodings all another encoding (non defining data) have leftjoin and it worked

here are screenshots when label was absent from frames

![image](https://user-images.githubusercontent.com/3648190/97817704-4a2ff700-1c9e-11eb-896d-d0595a34e336.png)

![image](https://user-images.githubusercontent.com/3648190/97817691-3e443500-1c9e-11eb-84f1-b477b7ce8576.png)

**Comment by jheeffer** [comment]
Should already be fixed in most cases since time is not in entityPropertyDataConfig.space anymore and thus it will be ammending (left join, no iteration) as long as time is in marker space.

Added additional check though:

```
if (fn === 'defining' && isIterable(this.encoding[name].data.response)) {
    defining.push(name);
}
```

Eventually we can make lookups iterable too by iterating over all combinations of lookup values; not sure if that's preferred behaviour though.
